language: ruby
rvm:
 - 2.2
 - 2.3.0
services:
  - postgresql
before_script:
  - psql -c "CREATE USER spnet2016 WITH PASSWORD 'spnet2016';" -U postgres
  - psql -c 'create database spnet2016_test;' -U postgres
  - psql -c "ALTER DATABASE spnet2016_test OWNER TO spnet2016;"
script: bundle exec rspec spec